### PR TITLE
Save memory in bse

### PR DESCRIPTION
**Pull request by Stefan-Dienst**
While calculating the lattice BSE for up to 12 bosonic frequencies I ran into memory problems on the cluster I use. I therefore implemented functionality to solve the lattice BSE for specific bosonic frequencies individually.

The new function for that is
https://github.com/TRIQS/tprf/blob/4a2cb7879d7704bc520ade71d1a104cd4fa0db94/python/triqs_tprf/bse.py#L362

and I test it here https://github.com/TRIQS/tprf/blob/f4576f54235e73cd252bf93cffce2ed7fec53dbe/test/python/solve_lattice_bse_at_specific_w.py .

### CODE REVIEW

**Comment by HugoStrand** [comment]
Dear Stefan,

Thank you for the contribution!

Cheers, Hugo

**Comment by Wentzell** [comment]
Dear @HugoStrand @StefanKaeser,

This was merged with tests still failing in the CI builds.
Could you please look into the test failures?

See e.g. the [jenkins/ubuntu-gcc](https://jenkins.flatironinstitute.org/job/TRIQS/view/unstable/job/tprf/job/unstable/443/execution/node/129/log/) test log or for all build environments:
https://jenkins.flatironinstitute.org/job/TRIQS/view/unstable/job/tprf/job/unstable/

**Comment by HugoStrand** [comment]
Dear @Wentzell,

Thank you for pointing out the failing tests. This should be fixed by 5ce04b0a9ab60d11c794f05cdcc52d8c2d5ba1fb.

Best, Hugo

**Comment by Wentzell** [comment]
Thank you @HugoStrand for looking into this!

**Pull request merged**
